### ISSUE TITLE
As an Employer, I want to be able to sign up and log into the Virtual Event platform so that I may gain access to Virtual MilitaryX Events

### ISSUE THREAD

**Issue by stanidesis** [talal-shahid/virtual-mx#15]
**Time Spent:**

Talal: 20 hours
Usman: 60 hours
Farsat: 20 hours

Total: 100 hours

---
- [x] 1. VMX Backend
  - [x] A. API to auth MX Employer @talal-shahid 
---
- [x] 2. MX Frontend
  - [x] A. Dashboard -> add new Virtual Events Tab
    - **Note:** we need to handle the pre-v1 state, as in, deactivated button with some sort of coming soon message!
    - [x] i. Copy @stanidesis 
    - [x] ii. Design @stanidesis 
    - [x] iii. Code Change @talal-shahid 
  - [x] B. Dashboard -> Refactor Default Dashboard
    - [x] i. Copy @stanidesis 
    - [x] ii. Page Coded @talal-shahid 
  - [x] C. Profile Page -> Headshot upload
    - [x] i. Copy @stanidesis 
    - [x] ii. Default image from @stanidesis 
    - [x] iii. Ability to upload headshot image @talal-shahid 
      - **Note:** automatically crop this to a square, approx 1000x1000
---
- [x] 3. MX Backend
  - [x] A. Store & retrieve headshot from Employer data @talal-shahid 
  - [x] B. Store & retrieve photos for each city @talal-shahid 
---
- [x] 4. VMX Frontend
  - [x] A. Login for Employers
    - **Note:** Logo, email, password, forgot password link, sign up button, sign up text, submit button, footer
    - [x] i. Copy @stanidesis 
    - [x] ii. Design @stanidesis 
    - [x] iii. Prepare HTML Template @talal-shahid 
    - [x] iv. Page(s) Coded @talal-shahid 

  - [x] B. Dashboard (navigation side-colum/hamburger menu w/header, 'My Events' -> list/grid of purchased Virtual Events, logout button, footer)
    - [x] i. Copy? @stanidesis 
    - [x] ii. Design @stanidesis 
    - [x] iii. Prepare HTML Template @talal-shahid 
    - [x] iv. Page(s) Coded @talal-shahid 
---
- [x] 5. MX Admin
  - [x] A. Allow admin to set the photo for each City @talal-shahid

**Comment by stanidesis** [comment]
@talal-shahid WIP design: https://xd.adobe.com/view/8f24c13a-2dac-41ed-6985-d7f8df49b794-f915/

**Comment by talal-shahid** [comment]
@stanidesis , please provide the assets required for this page, e.g. Logo etc

**Comment by stanidesis** [comment]
> @stanidesis , please provide the assets required for this page, e.g. Logo etc

I will soon!

**Comment by stanidesis** [comment]
@talal-shahid why did you close this? Was it on accident?
![image](https://user-images.githubusercontent.com/977088/77854976-1f833a80-71b3-11ea-8a64-227777051b1d.png)

**Comment by talal-shahid** [comment]
Hi, yes it got closed by accident. I tried re opening it but couldn’t find where to do it from

**Comment by stanidesis** [comment]
> Hi, yes it got closed by accident. Thanks for re-opening

A video explaining the Adobe XD tool for you guys: https://www.loom.com/share/f6bfd3d0a4954b6ca4ae2061297f0b13

**Comment by stanidesis** [comment]
@talal-shahid updated design: https://www.loom.com/share/79221ab9e96a41b1a78d0c7e6cfd1c90

I am still tweaking it, please reply with any questions/concerns or leave them in the design

**Comment by stanidesis** [comment]
@johnmiraglia we need to discuss city-images associated with each event.

**Comment by stanidesis** [comment]
@talal-shahid 

## 2.A.i & 2.A.ii
The tab should read `Virtual`.

Before V1 (so, _right now_) the button next to each virtual event should read, `Coming Soon` Below the button, can we have a fine-print text that reads, `We're hard at work building the perfect virtual dashboard for recruiters -- launching Summer 2020`

**Comment by stanidesis** [comment]
@talal-shahid 

# 2.B.i

The name of the default dashboard (current) should change to `In-Person`

**Comment by stanidesis** [comment]
@talal-shahid 

## 2.C.i

Text below current headshot (default): `Candidates will see this photo when communicating with you on our virtual platform. Use a professional and recent image.`
Button: `Upload New Headshot`

## 2.C.ii

![militaryx-default-employer-profile](https://user-images.githubusercontent.com/977088/78070369-43847e80-7361-11ea-8b0a-fce822a325e1.png)

**Comment by stanidesis** [comment]
City images in this archive:
[Virtual Career Fair City Images-20200406T160434Z-001.zip](https://github.com/talal-shahid/virtual-mx/files/4439544/Virtual.Career.Fair.City.Images-20200406T160434Z-001.zip)

**Comment by stanidesis** [comment]
## April 6, 2020

Talal:
- Polishing the avatar photo upload feature
- APIs connecting VMX and MX for authorization are 💯
- Sign-ins with & without email/pw 💯
- The 'My Events' dashboard on VMX is in progress
- Forgot my password -> 1-day away

Note: Talal is doing a great job delegating and making sure that all developers have something to work on independently. This current issue would otherwise have taken an extra week or two.

Aiming for review-ready on **Wednesday, April 8**.

Stanley:
- Updating the design and preparing for #17

**Comment by talal-shahid** [comment]
@stanidesis , currently on MX/JFX the big cities have been divided in East West North South. Is it going to be the same for the virtual events or we will just keep one big city?

**Comment by stanidesis** [comment]
> @stanidesis , currently on MX/JFX the big cities have been divided in East West North South. Is it going to be the same for the virtual events or we will just keep one big city?

Yes, use same images for each quadrant

**Comment by stanidesis** [comment]
## April 7, 2020

Stanley:
- Splitting large designs into sub-issues
- Finishing up Role creation and presentation in Booth

Talal:
- Profile picture is 💯
- Registered events pulled from MX is nearly-complete
- City Images uploaded
- Forgot Password API is done but needs integration
- Virtual/In-Person tabs ETA **tomorrow**

**Comment by stanidesis** [comment]
## April 8, 2020

Stanley:
- I continued to split up the design and tasks to reduce work and help prioritize features

Talal:
- Two hours away from Forgot Password (60-70%)
- Login API ran into an issue (1-2 hours away)
- Virtual/In-Person Tab was delayed due to Forgot Password
  - Stopped re-creating the functionality on VMX, so the email comes from MX

**Comment by stanidesis** [comment]
## April 9, 2020

Stanley:
- #17 design ready, waiting for approval
- Further organization and division between issues and design components

Talal:
- We did a demo with Usman, looking and working well (needs minor UI tweaks)
- Login and FP are at 💯
- Virtual tab is also at 💯
